### ISSUE TITLE
GitHub not up to date

### ISSUE THREAD

**Issue by dnrce** [chickenzord/hubot-mysql-brain#1]
- 0.1.3 is the latest version on npm
- 0.1.1 is the latest version in the commit log on GitHub
- 0.1.0 is the latest tagged version on GitHub

**Comment by akhy** [comment]
Hey Dan,

Thanks for pointing it out. I forget to push the latest change to Github.
Will push it on Monday.

**Comment by akhy** [comment]
Branch and tags pushed.
